/**
 * Database schema (spec section 4). Everything, including Better Auth's
 * tables, lives in the `attestly` Postgres schema so the database can be
 * dedicated or shared with other apps. The pgvector extension itself is
 * created by the first migration (in the database's default schema, usually
 * `public`), so `vector(768)` and the `<=>` operator resolve via search_path.
 *
 * Multi-tenancy is by `org_id` plus explicit `where` clauses in
 * `lib/db/repositories/*` (no row-level security). Every tenant table carries
 * `org_id`, even when it is derivable through a parent, so each query can
 * filter on it directly.
 *
 * Hand-written migrations (drizzle/):
 * - 0001_vector_indexes: chunks.tsv (generated tsvector), HNSW cosine indexes
 *   on both embedding columns, GIN on chunks.tsv.
 * - 0002_agent_events_append_only: trigger that rejects UPDATE, DELETE and
 *   TRUNCATE on agent_events.
 */
import { sql, type SQL } from "drizzle-orm";
import {
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgSchema,
  primaryKey,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  vector,
} from "drizzle-orm/pg-core";

export const attestly = pgSchema("attestly");

/** Gemini embeddings requested with `outputDimensionality: 768` (spec 4). */
export const EMBEDDING_DIMENSIONS = 768;

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

// ---------------------------------------------------------------------------
// Custom column types
// ---------------------------------------------------------------------------

/**
 * `bytea` as a Node Buffer. postgres.js returns Buffer, PGlite returns
 * Uint8Array; both are normalised to Buffer (no copy) so ExcelJS and
 * `Response` bodies accept it directly.
 */
export const bytea = customType<{ data: Buffer; driverData: Buffer | Uint8Array }>({
  dataType: () => "bytea",
  toDriver: (value) => value,
  fromDriver: (value) =>
    Buffer.isBuffer(value) ? value : Buffer.from(value.buffer, value.byteOffset, value.byteLength),
});

/** Read-only full-text vector (generated by Postgres). */
const tsvector = customType<{ data: string }>({ dataType: () => "tsvector" });

// ---------------------------------------------------------------------------
// Enums (value lists exported for zod schemas and UI)
// ---------------------------------------------------------------------------

export const PLANS = ["free", "pro"] as const;
export const MEMBERSHIP_ROLES = ["owner", "member"] as const;
export const DOCUMENT_KINDS = ["policy", "past_questionnaire", "pasted"] as const;
export const DOCUMENT_STATUSES = ["indexing", "ready", "failed"] as const;
export const LIBRARY_SOURCES = ["import", "questionnaire", "manual"] as const;
export const QUESTIONNAIRE_STATUSES = ["mapping", "drafting", "review", "done"] as const;
export const QUESTION_STATUSES = ["pending", "drafted", "needs_evidence", "not_applicable", "approved"] as const;
export const EMAIL_PROVIDERS = ["outbox", "resend"] as const;
export const OUTBOX_STATUSES = ["queued", "sent", "delivered", "failed"] as const;
export const ACTORS = ["agent", "user", "system", "cron", "webhook"] as const;

export const planEnum = attestly.enum("plan", PLANS);
export const membershipRoleEnum = attestly.enum("membership_role", MEMBERSHIP_ROLES);
export const documentKindEnum = attestly.enum("document_kind", DOCUMENT_KINDS);
export const documentStatusEnum = attestly.enum("document_status", DOCUMENT_STATUSES);
export const librarySourceEnum = attestly.enum("library_source", LIBRARY_SOURCES);
export const questionnaireStatusEnum = attestly.enum("questionnaire_status", QUESTIONNAIRE_STATUSES);
export const questionStatusEnum = attestly.enum("question_status", QUESTION_STATUSES);
export const emailProviderEnum = attestly.enum("email_provider", EMAIL_PROVIDERS);
export const outboxStatusEnum = attestly.enum("outbox_status", OUTBOX_STATUSES);
export const actorEnum = attestly.enum("actor", ACTORS);

// ---------------------------------------------------------------------------
// Better Auth core schema (v1.7). JS keys are Better Auth's field names (the
// adapter looks columns up by them); column names are snake_case.
// ---------------------------------------------------------------------------

export const user = attestly.table("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  /** Additional field (lib/auth/server.ts): names the organization created on sign-up. */
  businessName: text("business_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const session = attestly.table(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .$onUpdate(() => new Date()),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [index("session_user_id_idx").on(t.userId)],
);

export const account = attestly.table(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [index("account_user_id_idx").on(t.userId)],
);

export const verification = attestly.table(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)],
);

// ---------------------------------------------------------------------------
// Tenancy
// ---------------------------------------------------------------------------

export const organizations = attestly.table("organizations", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  plan: planEnum("plan").notNull().default("free"),
  stripeCustomerId: text("stripe_customer_id").unique(),
  stripeSubscriptionId: text("stripe_subscription_id").unique(),
  timezone: text("timezone").notNull().default("UTC"),
  createdAt: createdAt(),
});

export const memberships = attestly.table(
  "memberships",
  {
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    role: membershipRoleEnum("role").notNull().default("member"),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.orgId, t.userId] }), index("memberships_user_id_idx").on(t.userId)],
);

// ---------------------------------------------------------------------------
// Knowledge base
// ---------------------------------------------------------------------------

export const documents = attestly.table(
  "documents",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    kind: documentKindEnum("kind").notNull().default("policy"),
    fileName: text("file_name"),
    mimeType: text("mime_type"),
    sizeBytes: integer("size_bytes"),
    /** The uploaded file; null for pasted text. Never selected by list queries. */
    original: bytea("original"),
    /** Extracted plain text (Markdown-ish, headings preserved). */
    text: text("text").notNull().default(""),
    status: documentStatusEnum("status").notNull().default("indexing"),
    chunkCount: integer("chunk_count").notNull().default(0),
    error: text("error"),
    /**
     * Set when a re-index replaced this document. Superseded documents (and
     * their chunks) stay for citations in old answers but drop out of search.
     */
    supersededAt: timestamp("superseded_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("documents_org_created_idx").on(t.orgId, t.createdAt.desc()),
    index("documents_org_status_idx").on(t.orgId, t.status),
  ],
);

export const chunks = attestly.table(
  "chunks",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Order within the document, from 0. */
    position: integer("position").notNull(),
    /** Heading trail, e.g. ["Access Control", "2. Passwords"]. */
    headingPath: text("heading_path").array().notNull().default(sql`'{}'::text[]`),
    text: text("text").notNull(),
    tokenCount: integer("token_count").notNull().default(0),
    /** null until embedded (the daily cron retries failed embeddings). */
    embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
    /** Generated by Postgres from heading_path and text; never written by the app. */
    tsv: tsvector("tsv").generatedAlwaysAs(
      (): SQL =>
        sql`setweight(to_tsvector('english'::regconfig, coalesce(attestly.immutable_join(heading_path), '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce("text", '')), 'B')`,
    ),
    createdAt: createdAt(),
  },
  (t) => [
    index("chunks_document_position_idx").on(t.documentId, t.position),
    index("chunks_org_idx").on(t.orgId),
    index("chunks_embedding_hnsw_idx").using("hnsw", t.embedding.op("vector_cosine_ops")),
    index("chunks_tsv_gin_idx").using("gin", t.tsv),
  ],
);

export type CitationRef = {
  /** Exactly one of chunkId / libraryAnswerId is set. */
  chunkId?: string;
  libraryAnswerId?: string;
  /** Verbatim passage from the cited text (validated by lib/draft guardrails). */
  quote: string;
};

export const libraryAnswers = attestly.table(
  "library_answers",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    source: librarySourceEnum("source").notNull().default("manual"),
    questionnaireId: uuid("questionnaire_id").references(() => questionnaires.id, { onDelete: "set null" }),
    /** The approved question this answer came from; unique so re-approving updates in place. */
    questionId: uuid("question_id").references(() => questions.id, { onDelete: "set null" }),
    /** Embedding of the question text; null until embedded. */
    embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
    approvedAt: timestamp("approved_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("library_answers_org_created_idx").on(t.orgId, t.createdAt.desc()),
    uniqueIndex("library_answers_question_key").on(t.questionId).where(sql`${t.questionId} is not null`),
    index("library_answers_embedding_hnsw_idx").using("hnsw", t.embedding.op("vector_cosine_ops")),
  ],
);

// ---------------------------------------------------------------------------
// Questionnaires
// ---------------------------------------------------------------------------

export const questionnaires = attestly.table(
  "questionnaires",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    customer: text("customer"),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type").notNull(),
    /** The customer's workbook (XLSX) or CSV, kept for round-trip export. Never selected by list queries. */
    original: bytea("original").notNull(),
    /** Worksheet name; null for CSV. */
    sheetName: text("sheet_name"),
    /** 1-based row and column numbers (ExcelJS convention); null until the mapping is confirmed. */
    headerRow: integer("header_row"),
    idCol: integer("id_col"),
    questionCol: integer("question_col"),
    answerCol: integer("answer_col"),
    commentCol: integer("comment_col"),
    status: questionnaireStatusEnum("status").notNull().default("mapping"),
    questionCount: integer("question_count").notNull().default(0),
    draftedCount: integer("drafted_count").notNull().default(0),
    approvedCount: integer("approved_count").notNull().default(0),
    needsEvidenceCount: integer("needs_evidence_count").notNull().default(0),
    /** Read-only review link id (Pro); null when not shared. */
    publicId: text("public_id").unique(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("questionnaires_org_created_idx").on(t.orgId, t.createdAt.desc()),
    index("questionnaires_org_status_idx").on(t.orgId, t.status),
  ],
);

export const questions = attestly.table(
  "questions",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    questionnaireId: uuid("questionnaire_id")
      .notNull()
      .references(() => questionnaires.id, { onDelete: "cascade" }),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** 1-based worksheet row; the answer is written back to (row_number, questionnaires.answer_col). */
    rowNumber: integer("row_number").notNull(),
    section: text("section"),
    /** The customer's own question id (e.g. "AC-03"), when the sheet has one. */
    externalId: text("external_id"),
    text: text("text").notNull(),
    /** Model draft, as generated (after guardrails). */
    draft: text("draft"),
    /** Reviewer's final answer (edited or accepted draft); what gets exported. */
    final: text("final"),
    status: questionStatusEnum("status").notNull().default("pending"),
    /** 0..1 */
    confidence: real("confidence"),
    citations: jsonb("citations").$type<CitationRef[]>().notNull().default([]),
    /** What retrieval returned (ids and scores), for audit and the citation panel. */
    retrieval: jsonb("retrieval").$type<Record<string, unknown>>(),
    /** Model note (e.g. which document would answer it) or the reviewer's task text. */
    notes: text("notes"),
    reviewedBy: text("reviewed_by").references(() => user.id, { onDelete: "set null" }),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("questions_questionnaire_row_idx").on(t.questionnaireId, t.rowNumber),
    index("questions_questionnaire_status_idx").on(t.questionnaireId, t.status),
    index("questions_org_status_idx").on(t.orgId, t.status),
  ],
);

export const shareLinks = attestly.table(
  "share_links",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    questionnaireId: uuid("questionnaire_id")
      .notNull()
      .references(() => questionnaires.id, { onDelete: "cascade" }),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Unguessable url-safe id for /s/<public_id>. */
    publicId: text("public_id").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    index("share_links_questionnaire_idx").on(t.questionnaireId),
    index("share_links_expires_idx").on(t.expiresAt),
  ],
);

// ---------------------------------------------------------------------------
// Email and audit
// ---------------------------------------------------------------------------

export const outbox = attestly.table(
  "outbox",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** e.g. "welcome", "drafting_done". */
    kind: text("kind"),
    toEmail: text("to_email").notNull(),
    subject: text("subject").notNull(),
    html: text("html"),
    text: text("text").notNull(),
    provider: emailProviderEnum("provider").notNull().default("outbox"),
    providerMessageId: text("provider_message_id"),
    /** Where the message actually went (differs from to_email in demo mode). */
    deliveredTo: text("delivered_to"),
    status: outboxStatusEnum("status").notNull().default("queued"),
    createdAt: createdAt(),
  },
  (t) => [index("outbox_org_created_idx").on(t.orgId, t.createdAt.desc())],
);

export const agentEvents = attestly.table(
  "agent_events",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    /** null for system events not tied to an organization (e.g. cron sweeps). */
    orgId: uuid("org_id").references(() => organizations.id, { onDelete: "cascade" }),
    actor: actorEnum("actor").notNull(),
    type: text("type").notNull(),
    entityType: text("entity_type"),
    entityId: uuid("entity_id"),
    input: jsonb("input"),
    output: jsonb("output"),
    model: text("model"),
    promptVersion: text("prompt_version"),
    tokensIn: integer("tokens_in"),
    tokensOut: integer("tokens_out"),
    latencyMs: integer("latency_ms"),
    createdAt: createdAt(),
  },
  (t) => [
    index("agent_events_org_created_idx").on(t.orgId, t.createdAt.desc()),
    index("agent_events_entity_idx")
      .on(t.entityType, t.entityId, t.createdAt.desc())
      .where(sql`${t.entityId} is not null`),
  ],
);
