-- Retrieval indexes (spec 4). Generated by drizzle-kit from lib/db/schema.ts,
-- then hand-edited: the helper function below must exist before the
-- generated column that uses it.
--
-- array_to_string() is STABLE (it calls element output functions), which a
-- generated column cannot use. For text[] it is deterministic, so this thin
-- wrapper is declared IMMUTABLE.
CREATE OR REPLACE FUNCTION "attestly"."immutable_join"(text[])
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $$ SELECT pg_catalog.array_to_string($1, ' ') $$;
--> statement-breakpoint
-- Full-text vector: heading trail weighted A, body weighted B.
ALTER TABLE "attestly"."chunks" ADD COLUMN "tsv" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english'::regconfig, coalesce(attestly.immutable_join(heading_path), '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce("text", '')), 'B')) STORED;--> statement-breakpoint
-- HNSW (cosine) on both embedding columns; GIN on the tsvector.
CREATE INDEX "chunks_embedding_hnsw_idx" ON "attestly"."chunks" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "chunks_tsv_gin_idx" ON "attestly"."chunks" USING gin ("tsv");--> statement-breakpoint
CREATE INDEX "library_answers_embedding_hnsw_idx" ON "attestly"."library_answers" USING hnsw ("embedding" vector_cosine_ops);
